spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imvc?createDatabaseIfNotExist=true
    username: root
    password: apj_cn
    #    url: jdbc:mysql://47.107.122.213:3306/zhonghaida?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #    username: sh0312
#    password: ZhdGps-2019
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    view:
#      prefix: *
#      suffix: .html
  thymeleaf:
    cache: false # Enable templates caching.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    excluded-view-names: # Comma-separated list of view names that should be excluded from resolution.
#    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    mode: LEGACYHTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
    template-resolver-order: # Order of the templates resolver in the chain. spring.thymeleaf.view-names= # Comma-separated list of view names that can be resolved.
#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml


#security:
#  user:
#    name: myOwnUser
#    password: myOwnPassword
#    role: ADMIN
