server:
  port: 8088
spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/imvc?createDatabaseIfNotExist=true
    username: root
    password: apj_cn
    #    url: jdbc:mysql://47.107.122.213:3306/zhonghaida?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #    username: sh0312
#    password: ZhdGps-2019
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  redis:
    database: 1  # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）root
    timeout: 200 # 连接超时时间（毫秒）
    pool:
      max-idle: 8  # 连接池中的最大空闲连接
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
#      min-idle: 0   # 连接池中的最小空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #  mvc:
  #    view:
  #      prefix: *
  #      suffix: .html
  thymeleaf:
    cache: false # Enable thymeTmpl caching.
    check-template-location: true # Check that the thymeTmpl location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    excluded-view-names: # Comma-separated list of view names that should be excluded from resolution.
    #    mode: HTML5 # Template mode to be applied to thymeTmpl. See also StandardTemplateModeHandlers.
    mode: LEGACYHTML5 # Template mode to be applied to thymeTmpl. See also StandardTemplateModeHandlers.
    prefix: classpath:/thymeTmpl/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
    template-resolver-order: # Order of the thymeTmpl resolver in the chain. spring.thymeleaf.view-names= # Comma-separated list of view names that can be resolved.
#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml


#security:
#  user:
#    name: myOwnUser
#    password: myOwnPassword
#    role: ADMIN
#lgx:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
job:
  calculateTriggerCron: 0 0 23 * * ?   #秒，分钟，小时，天，月，年，星期 ,这个配置的意思是 每天的 23：0：0

